### ISSUE TITLE
rob, they seem to have broken filter aiohttp.client_exceptions.ClientResponseError: 420, message='Unknown', url=URL('https://stream.twitter.com/1.1/statuses/filter.json')

### ISSUE THREAD

**Issue by markmark1** [rob-blackbourn/jetblack-tweeter#8]
running on mac osx m1, python 3.9 latest HEAD of src from GitHub https://github.com/rob-blackbourn/jetblack-tweeter 

mark@m1-macpro-aug17 ~ $ python3 --version
Python 3.8.2
mark@m1-macpro-aug17 ~ $ python3.9 --version
Python 3.9.6

Traceback (most recent call last):
  File "strm.py", line 121, in <module>
    asyncio.run(main())
  File "/python3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/python3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "strm.py", line 108, in main
    async for tweet in tweeter.stream.filter(
  File "/python3.9/site-packages/jetblack_tweeter/api/stream.py", line 68, in filter
    async for message in self._client.stream(url, body):
  File "/python3.9/site-packages/jetblack_tweeter/clients/aiohttp/session.py", line 30, in stream
    response.raise_for_status()
  File "/python3.9/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 420, message='Unknown', url=URL('https://stream.twitter.com/1.1/statuses/filter.json')
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10bbfdd90>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x10bc251c0>, 1.13466706)]']
connector: <aiohttp.connector.TCPConnector object at 0x10bbfdd30>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10bc03ac0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x10bccbbe0>, 1.451231511)]']
connector: <aiohttp.connector.TCPConnector object at 0x10bc03520>

**Comment by rob-blackbourn** [comment]
I think 420 is rate limiting. I'll address the other issues on the other thread.
